(defun color-theme-rdark ()
  "Color theme by Marcus Crafter, based off the TextMate Twilight theme, created 2008-04-18"
  (interactive)
  (color-theme-install
	'(color-theme-rdark
          ((background-color . "#1e2426")
		(background-mode . dark)
		(border-color . "black")
		(cursor-color . "red")
		(foreground-color . "#babdb6")
		(mouse-color . "sienna1"))
          (default ((t (:background "#1e2426" :foreground "#babdb6"))))
          (blue ((t (:foreground "blue"))))
          (border-glyph ((t (nil))))
          (buffers-tab ((t (:background "#1e2426" :foreground "#babdb6"))))
          (font-lock-builtin-face ((t (:foreground "#"))))
          (font-lock-comment-face ((t (:foreground "#656763"))))
          (font-lock-constant-face ((t (:foreground "#8ae234"))))
          (font-lock-doc-string-face ((t (:foreground "#fc6500"))))
          (font-lock-function-name-face ((t (:foreground "#fc6500"))))
          (font-lock-keyword-face ((t (:foreground "#fcaf3e"))))
          (font-lock-preprocessor-face ((t (:foreground "red"))))
          (font-lock-reference-face ((t (:foreground "#729FCF"))))

          (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
          (font-lock-regexp-grouping-construct ((t (:foreground "red"))))

          (minibuffer-prompt ((t (:foreground "#5F5A60"))))
          (ido-subdir ((t (:foreground "#CF6A4C"))))
          (ido-first-match ((t (:foreground "#8F9D6A"))))
          (ido-only-match ((t (:foreground "#8F9D6A"))))
          (mumamo-background-chunk-submode ((t (:background "#222222"))))

          (font-lock-string-face ((t (:foreground "#8F9D6A"))))
          (font-lock-type-face ((t (:foreground "#ffffff"))))
          (font-lock-variable-name-face ((t (:foreground "#63A0D3"))))
          (font-lock-warning-face ((t (:background "#EE799F" :foreground "red"))))
          (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
          (region ((t (:background "#54585a"))))
          (mode-line ((t (:background "grey75" :foreground "black"))))
          (highlight ((t (:background "#111111"))))
          (highline-face ((t (:background "SeaGreen"))))
          (left-margin ((t (nil))))
          (text-cursor ((t (:background "yellow" :foreground "black"))))
          (toolbar ((t (nil))))
          (underline ((nil (:underline nil))))
          (zmacs-region ((t (:background "snow" :foreground "blue")))))))